### PR TITLE
Using built in style

### LINKED ISSUE #1: Poor contrast in dark style
The sun and moon and settings icons have really poor contrast in dark style.

image

### PR DESCRIPTION
**Pull request by lukors**
fixes #1

This PR removes the custom css and uses a built in style for the "select a default wallpaper" title.

It looks different, so if you care about that I can look at if there is a built in text style that more closely matches, or maybe using custom css for that is the way to go.

The motivation for this change is to improve contrast (both in dark mode and light mode).

# Preview
### Before
Before light

### After
After light

### Before
Before dark

### After
After dark

### CODE REVIEW

**Comment by JeysonFlores** [comment]
I like the titles in thin font, however they're too small, it'll be nice if they're bigger. I like the way the ModeButton looks without the custom CSS, however in order to make a custom text style for the title, there's no need to delete the .css files.

**Comment by lukors** [comment]
The title font has been increased in size, now using H2 instead of H3.

Skärmbild från 2021-12-16 00-45-16
It's true that there is no need to delete the .css files. However, if you like how it looks without the .css files there is no reason to keep them around either, because they are not hooked up to anything.

They will always be around in the git history if they are needed.

**Comment by JeysonFlores** [comment]
That's better. I will give it a try to see how it looks in my screen.

**Comment by JeysonFlores** [comment]
look good to me. Merged it

**Pull request merged**
